language: python

stages:
  - linting
  - test
  - codecov

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

before_install:
  - sudo apt-get install -y libev-dev

install:
  - pip install pip==18.1
  - pip install poetry
  - poetry install -v

script: pytest -q tests/


linting:
  stage: linting
  script:
    - echo "asd"