language: python

stages:
  - linting
  - test
  - codecov

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

before_install:
  - sudo apt-get install -y libev-dev

install:
  - pip install pip==18.1
  - pip install poetry
  - poetry install -v

script: pytest -q tests/

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: codecov
      python: "3.6"
      script:
        - pytest --ignore venv -W ignore::DeprecationWarning --cov=opyapi --cov=tests --cov-report=term-missing
        - pip install codecov
        - codecov
