language: python

stages:
  - linting
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

before_install:
  - sudo apt-get install -y libev-dev

install:
  - pip install pip==18.1
  - pip install poetry
  - poetry install -v

script: pytest -q tests/

jobs:
  include:
    - python: "3.7"
      dist: xenial

    - stage: linting
      python: "3.7"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
